// Copyright 2026 André Cipriani Bandarra
// SPDX-License-Identifier: Apache-2.0

use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::types::{
    jsonrpc::{JsonRpcRequest, JsonRpcResultResponse},
    mcp::{ContentBlock, RequestMetaObject, ResultMetaObject, TextContent},
};

pub type CallToolRequest<A = Value> = JsonRpcRequest<CallToolParams<A>>;
pub type CallToolResultResponse<S = Value> = JsonRpcResultResponse<CallToolResult<S>>;

/// Parameters for a `tools/call` request.
///
/// See <https://modelcontextprotocol.io/specification/2026-07-28/schema#calltoolrequest>
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CallToolParams<A = Value>  {
    /// Protocol-level request metadata.
    #[serde(rename = "_meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<RequestMetaObject>,
    /// The name of the tool to call.
    pub name: String,
    /// Arguments to pass to the tool.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arguments: Option<A>,
    /// Additional unrecognized or custom metadata properties.
    #[serde(flatten, skip_serializing_if = "HashMap::is_empty")]
    pub extras: HashMap<String, Value>,
}

/// The server's response to a `tools/call` request.
///
/// See <https://modelcontextprotocol.io/specification/2026-07-28/schema#calltoolresult>
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CallToolResult<S = Value> {
    /// Protocol-level response metadata.
    #[serde(rename = "_meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<ResultMetaObject>,
    /// Result type discriminator string.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result_type: Option<String>,
    /// Content generated by the tool call.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub content: Vec<ContentBlock>,
    /// Whether the tool execution resulted in an error.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_error: Option<bool>,
    /// Structured output data, if provided by the tool.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub structured_content: Option<S>,
    /// Additional unrecognized or custom metadata properties.
    #[serde(flatten, skip_serializing_if = "HashMap::is_empty")]
    pub extras: HashMap<String, Value>,
}

impl<S> CallToolResult<S> {
    pub fn text(text: impl Into<String>) -> Self {
        Self {
            meta: None,
            result_type: Some("complete".to_string()),
            content: vec![ContentBlock::Text(TextContent {
                text: text.into(),
                annotations: None,
                meta: None,
            })],
            is_error: Some(false),
            structured_content: None,
            extras: HashMap::new(),
        }
    }

    pub fn error(message: impl Into<String>) -> Self {
        Self {
            meta: None,
            result_type: Some("complete".to_string()),
            content: vec![ContentBlock::Text(TextContent {
                text: message.into(),
                annotations: None,
                meta: None,
            })],
            is_error: Some(true),
            structured_content: None,
            extras: HashMap::new(),
        }
    }

    pub fn with_content(content: Vec<ContentBlock>) -> Self {
        Self {
            meta: None,
            result_type: Some("complete".to_string()),
            content,
            is_error: Some(false),
            structured_content: None,
            extras: HashMap::new(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_call_tool_request_serde() {
        let json_data = serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/call",
            "params": {
                "name": "echo",
                "arguments": {
                    "value": "hello"
                }
            }
        });

        let req: CallToolRequest = serde_json::from_value(json_data).unwrap();
        assert_eq!(req.method, "tools/call");
        let params = req.params.unwrap();
        assert_eq!(params.name, "echo");
        assert_eq!(params.arguments.unwrap()["value"], "hello");
    }

    #[test]
    fn test_call_tool_result_serde() {
        let json_data = serde_json::json!({
            "resultType": "complete",
            "content": [{
                "type": "text",
                "text": "Hello"
            }],
            "isError": false
        });

        let result: CallToolResult = serde_json::from_value(json_data).unwrap();
        assert_eq!(result.result_type.as_deref(), Some("complete"));
        assert_eq!(result.content.len(), 1);
        if let ContentBlock::Text(ref text_content) = result.content[0] {
            assert_eq!(text_content.text, "Hello");
        } else {
            panic!("Expected ContentBlock::Text");
        }
        assert_eq!(result.is_error, Some(false));

        let reserialized = serde_json::to_value(&result).unwrap();
        assert_eq!(reserialized["isError"], false);
        assert_eq!(reserialized["content"][0]["type"], "text");
        assert_eq!(reserialized["content"][0]["text"], "Hello");
    }
}
