// Copyright 2026 André Cipriani Bandarra
// SPDX-License-Identifier: Apache-2.0

use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::types::{
    jsonrpc::{JsonRpcRequest, JsonRpcResultResponse},
    mcp::{
        AudioContent, ContentBlock, ImageContent, RequestMetaObject, ResultMetaObject, TextContent,
    },
};

pub type CallToolRequest<A = Value> = JsonRpcRequest<CallToolParams<A>>;
pub type CallToolResultResponse<S = Value> = JsonRpcResultResponse<CallToolResult<S>>;

/// Parameters for a `tools/call` request.
///
/// See <https://modelcontextprotocol.io/specification/2026-07-28/schema#calltoolrequest>
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CallToolParams<A = Value> {
    /// Protocol-level request metadata.
    #[serde(rename = "_meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<RequestMetaObject>,
    /// The name of the tool to call.
    pub name: String,
    /// Arguments to pass to the tool.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arguments: Option<A>,
    /// Additional unrecognized or custom metadata properties.
    #[serde(flatten, skip_serializing_if = "HashMap::is_empty")]
    pub extras: HashMap<String, Value>,
}

impl<A> CallToolParams<A> {
    /// Returns the MRTR request state from params if present.
    pub fn request_state(&self) -> Option<&str> {
        self.extras.get("requestState").and_then(|v| v.as_str())
    }

    /// Returns the MRTR input responses from params if present.
    pub fn input_responses(&self) -> Option<HashMap<String, crate::types::mcp::InputResponse>> {
        self.extras
            .get("inputResponses")
            .cloned()
            .and_then(|v| serde_json::from_value(v).ok())
    }

    /// Sets the MRTR request state in params.
    pub fn with_request_state(mut self, state: impl Into<String>) -> Self {
        self.extras
            .insert("requestState".to_string(), Value::String(state.into()));
        self
    }

    /// Sets the MRTR input responses in params.
    pub fn with_input_responses(
        mut self,
        responses: HashMap<String, crate::types::mcp::InputResponse>,
    ) -> Self {
        if let Ok(v) = serde_json::to_value(responses) {
            self.extras.insert("inputResponses".to_string(), v);
        }
        self
    }
}

/// The server's response to a `tools/call` request.
///
/// See <https://modelcontextprotocol.io/specification/2026-07-28/schema#calltoolresult>
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CallToolResult<S = Value> {
    /// Protocol-level response metadata.
    #[serde(rename = "_meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<ResultMetaObject>,
    /// Result type discriminator string.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result_type: Option<String>,
    /// Content generated by the tool call.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub content: Vec<ContentBlock>,
    /// Whether the tool execution resulted in an error.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_error: Option<bool>,
    /// Structured output data, if provided by the tool.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub structured_content: Option<S>,
    /// Additional unrecognized or custom metadata properties.
    #[serde(flatten, skip_serializing_if = "HashMap::is_empty")]
    pub extras: HashMap<String, Value>,
}

impl<S> Default for CallToolResult<S> {
    fn default() -> Self {
        Self {
            meta: None,
            result_type: Some("complete".to_string()),
            content: Vec::new(),
            is_error: Some(false),
            structured_content: None,
            extras: HashMap::new(),
        }
    }
}

impl CallToolResult<Value> {
    /// Creates a new successful [`CallToolResult`] with empty content.
    pub fn new() -> Self {
        Self::default()
    }

    /// Creates a successful [`CallToolResult`] containing a single text content block.
    pub fn text(text: impl Into<String>) -> Self {
        Self {
            meta: None,
            result_type: Some("complete".to_string()),
            content: vec![ContentBlock::Text(TextContent {
                text: text.into(),
                annotations: None,
                meta: None,
            })],
            is_error: Some(false),
            structured_content: None,
            extras: HashMap::new(),
        }
    }

    /// Creates an error [`CallToolResult`] containing a single text content block with the error message.
    pub fn error(message: impl Into<String>) -> Self {
        Self {
            meta: None,
            result_type: Some("complete".to_string()),
            content: vec![ContentBlock::Text(TextContent {
                text: message.into(),
                annotations: None,
                meta: None,
            })],
            is_error: Some(true),
            structured_content: None,
            extras: HashMap::new(),
        }
    }

    /// Creates a successful [`CallToolResult`] with the provided content blocks.
    pub fn with_content(content: impl Into<Vec<ContentBlock>>) -> Self {
        Self {
            meta: None,
            result_type: Some("complete".to_string()),
            content: content.into(),
            is_error: Some(false),
            structured_content: None,
            extras: HashMap::new(),
        }
    }

    /// Creates a successful [`CallToolResult`] by serializing any serializable value into [`Value`].
    pub fn structured_json<T: Serialize>(value: &T) -> Result<Self, serde_json::Error> {
        let structured_content = serde_json::to_value(value)?;
        Ok(Self::structured(structured_content))
    }

    /// Creates a successful [`CallToolResult`] containing both serialized structured JSON and a text message.
    pub fn structured_json_with_text<T: Serialize>(
        value: &T,
        text: impl Into<String>,
    ) -> Result<Self, serde_json::Error> {
        let structured_content = serde_json::to_value(value)?;
        Ok(Self::structured_with_text(structured_content, text))
    }

    /// Creates a successful [`CallToolResult`] containing both serialized structured JSON and content blocks.
    pub fn structured_json_with_content<T: Serialize>(
        value: &T,
        content: impl Into<Vec<ContentBlock>>,
    ) -> Result<Self, serde_json::Error> {
        let structured_content = serde_json::to_value(value)?;
        Ok(Self::structured_with_content(structured_content, content))
    }

    /// Creates an `InputRequiredResult`-style [`CallToolResult`] indicating that additional client input is needed (MRTR).
    pub fn input_required(
        input_requests: HashMap<String, crate::types::mcp::InputRequest>,
        request_state: Option<String>,
    ) -> Self {
        let mut extras = HashMap::new();
        if let Some(state) = request_state {
            extras.insert("requestState".to_string(), Value::String(state));
        }
        if !input_requests.is_empty()
            && let Ok(v) = serde_json::to_value(input_requests)
        {
            extras.insert("inputRequests".to_string(), v);
        }
        Self {
            meta: None,
            result_type: Some("input_required".to_string()),
            content: Vec::new(),
            is_error: None,
            structured_content: None,
            extras,
        }
    }

    /// Creates an `InputRequiredResult`-style [`CallToolResult`] for load shedding with only an opaque request state (MRTR).
    pub fn load_shed(request_state: impl Into<String>) -> Self {
        let mut extras = HashMap::new();
        extras.insert(
            "requestState".to_string(),
            Value::String(request_state.into()),
        );
        Self {
            meta: None,
            result_type: Some("input_required".to_string()),
            content: Vec::new(),
            is_error: None,
            structured_content: None,
            extras,
        }
    }
}

impl<S> CallToolResult<S> {
    /// Creates a successful [`CallToolResult`] with structured output data.
    pub fn structured(data: S) -> Self {
        Self {
            meta: None,
            result_type: Some("complete".to_string()),
            content: Vec::new(),
            is_error: Some(false),
            structured_content: Some(data),
            extras: HashMap::new(),
        }
    }

    /// Creates a successful [`CallToolResult`] containing both structured output data and a text message.
    pub fn structured_with_text(data: S, text: impl Into<String>) -> Self {
        Self {
            meta: None,
            result_type: Some("complete".to_string()),
            content: vec![ContentBlock::Text(TextContent {
                text: text.into(),
                annotations: None,
                meta: None,
            })],
            is_error: Some(false),
            structured_content: Some(data),
            extras: HashMap::new(),
        }
    }

    /// Creates a successful [`CallToolResult`] containing both structured output data and content blocks.
    pub fn structured_with_content(data: S, content: impl Into<Vec<ContentBlock>>) -> Self {
        Self {
            meta: None,
            result_type: Some("complete".to_string()),
            content: content.into(),
            is_error: Some(false),
            structured_content: Some(data),
            extras: HashMap::new(),
        }
    }

    /// Sets or replaces the structured content payload.
    pub fn structured_content(mut self, structured: S) -> Self {
        self.structured_content = Some(structured);
        self
    }

    /// Transforms this result into a [`CallToolResult<T>`] with the specified structured content.
    pub fn with_structured<T>(self, structured: T) -> CallToolResult<T> {
        CallToolResult {
            meta: self.meta,
            result_type: self.result_type,
            content: self.content,
            is_error: self.is_error,
            structured_content: Some(structured),
            extras: self.extras,
        }
    }

    /// Sets the protocol-level metadata for this result.
    pub fn with_meta(mut self, meta: ResultMetaObject) -> Self {
        self.meta = Some(meta);
        self
    }

    /// Sets the result type discriminator string.
    pub fn with_result_type(mut self, result_type: impl Into<String>) -> Self {
        self.result_type = Some(result_type.into());
        self
    }

    /// Returns `true` if this result indicates additional input is required (`resultType == "input_required"`).
    pub fn is_input_required(&self) -> bool {
        self.result_type.as_deref() == Some("input_required")
    }

    /// Returns the MRTR request state if present in the result.
    pub fn request_state(&self) -> Option<&str> {
        self.extras.get("requestState").and_then(|v| v.as_str())
    }

    /// Returns the MRTR input requests if present in the result.
    pub fn input_requests(&self) -> Option<HashMap<String, crate::types::mcp::InputRequest>> {
        self.extras
            .get("inputRequests")
            .cloned()
            .and_then(|v| serde_json::from_value(v).ok())
    }

    /// Sets whether the tool execution resulted in an error.
    pub fn with_error(mut self, is_error: bool) -> Self {
        self.is_error = Some(is_error);
        self
    }

    /// Appends a text content block to the result.
    pub fn with_text(mut self, text: impl Into<String>) -> Self {
        self.content.push(ContentBlock::Text(TextContent {
            text: text.into(),
            annotations: None,
            meta: None,
        }));
        self
    }

    /// Appends an image content block to the result.
    pub fn with_image(mut self, data: impl Into<String>, mime_type: impl Into<String>) -> Self {
        self.content.push(ContentBlock::Image(ImageContent {
            data: data.into(),
            mime_type: mime_type.into(),
            annotations: None,
            meta: None,
        }));
        self
    }

    /// Appends an audio content block to the result.
    pub fn with_audio(mut self, data: impl Into<String>, mime_type: impl Into<String>) -> Self {
        self.content.push(ContentBlock::Audio(AudioContent {
            data: data.into(),
            mime_type: mime_type.into(),
            annotations: None,
            meta: None,
        }));
        self
    }

    /// Appends a generic [`ContentBlock`] to the result.
    pub fn with_block(mut self, block: impl Into<ContentBlock>) -> Self {
        self.content.push(block.into());
        self
    }

    /// Appends multiple content blocks to the result.
    pub fn with_blocks(mut self, blocks: impl IntoIterator<Item = ContentBlock>) -> Self {
        self.content.extend(blocks);
        self
    }

    /// Adds a key-value pair to the extras metadata map.
    pub fn with_extra(mut self, key: impl Into<String>, value: impl Into<Value>) -> Self {
        self.extras.insert(key.into(), value.into());
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_call_tool_request_serde() {
        let json_data = serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/call",
            "params": {
                "name": "echo",
                "arguments": {
                    "value": "hello"
                }
            }
        });

        let req: CallToolRequest = serde_json::from_value(json_data).unwrap();
        assert_eq!(req.method, "tools/call");
        let params = req.params.unwrap();
        assert_eq!(params.name, "echo");
        assert_eq!(params.arguments.unwrap()["value"], "hello");
    }

    #[test]
    fn test_call_tool_result_serde() {
        let json_data = serde_json::json!({
            "resultType": "complete",
            "content": [{
                "type": "text",
                "text": "Hello"
            }],
            "isError": false,
            "structuredContent": {
                "key": "value"
            }
        });

        let result: CallToolResult = serde_json::from_value(json_data).unwrap();
        assert_eq!(result.result_type.as_deref(), Some("complete"));
        assert_eq!(result.content.len(), 1);
        if let ContentBlock::Text(ref text_content) = result.content[0] {
            assert_eq!(text_content.text, "Hello");
        } else {
            panic!("Expected ContentBlock::Text");
        }
        assert_eq!(result.is_error, Some(false));
        assert_eq!(result.structured_content.as_ref().unwrap()["key"], "value");

        let reserialized = serde_json::to_value(&result).unwrap();
        assert_eq!(reserialized["isError"], false);
        assert_eq!(reserialized["content"][0]["type"], "text");
        assert_eq!(reserialized["content"][0]["text"], "Hello");
        assert_eq!(reserialized["structuredContent"]["key"], "value");
    }

    /// Tests [`CallToolResult`] convenience constructors and builder methods.
    #[test]
    fn test_call_tool_result_builder_constructors() {
        let text_res = CallToolResult::<serde_json::Value>::text("Hello result");
        assert_eq!(text_res.result_type.as_deref(), Some("complete"));
        assert_eq!(text_res.is_error, Some(false));
        assert_eq!(text_res.content.len(), 1);

        let err_res = CallToolResult::<serde_json::Value>::error("Failure message");
        assert_eq!(err_res.result_type.as_deref(), Some("complete"));
        assert_eq!(err_res.is_error, Some(true));
        assert_eq!(err_res.content.len(), 1);

        let block = ContentBlock::Text(TextContent {
            text: "block".to_string(),
            annotations: None,
            meta: None,
        });
        let with_content_res =
            CallToolResult::<serde_json::Value>::with_content(vec![block.clone()]);
        assert_eq!(with_content_res.is_error, Some(false));
        assert_eq!(with_content_res.content.len(), 1);

        // Structured constructors
        let struct_res = CallToolResult::structured(serde_json::json!({ "status": "ok" }));
        assert_eq!(struct_res.structured_content.unwrap()["status"], "ok");
        assert!(struct_res.content.is_empty());

        let struct_text_res = CallToolResult::structured_with_text(
            serde_json::json!({ "count": 10 }),
            "Found 10 items",
        );
        assert_eq!(struct_text_res.structured_content.unwrap()["count"], 10);
        assert_eq!(struct_text_res.content.len(), 1);

        let struct_content_res =
            CallToolResult::structured_with_content(serde_json::json!({ "id": 1 }), vec![block]);
        assert_eq!(struct_content_res.structured_content.unwrap()["id"], 1);
        assert_eq!(struct_content_res.content.len(), 1);

        // JSON helper constructors
        #[derive(Serialize)]
        struct Person {
            name: String,
            age: u32,
        }
        let person = Person {
            name: "Alice".to_string(),
            age: 30,
        };

        let json_res = CallToolResult::structured_json(&person).unwrap();
        assert_eq!(json_res.structured_content.unwrap()["name"], "Alice");

        let json_text_res =
            CallToolResult::structured_json_with_text(&person, "Person created").unwrap();
        assert_eq!(json_text_res.structured_content.unwrap()["age"], 30);
        assert_eq!(json_text_res.content.len(), 1);

        // Fluent builders
        let chained = CallToolResult::new()
            .with_text("Chained text")
            .with_image("aW1hZ2U=", "image/png")
            .with_audio("YXVkaW8=", "audio/wav")
            .with_extra("custom", serde_json::json!(42))
            .with_structured(serde_json::json!({ "chained": true }));

        assert_eq!(chained.content.len(), 3);
        assert_eq!(chained.extras.get("custom").unwrap(), 42);
        assert_eq!(chained.structured_content.unwrap()["chained"], true);
    }
}
